# Generated by Django 4.0.1 on 2022-01-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("articles", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="amount_of_upvotes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="upvotes count"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author_name",
            field=models.CharField(default="anonymous", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="link",
            field=models.SlugField(max_length=200, verbose_name="Link to post"),
        ),
        migrations.CreateModel(
            name="Upvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="articles.post",
                    ),
                ),
            ],
            options={"ordering": ["-id"]},
        ),
    ]
