# Generated by Django 4.0.1 on 2022-01-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_comment_options_alter_post_options_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="amount_of_upvotes",
            field=models.IntegerField(default=0, verbose_name="upvotes count"),
        )
    ]
