# Generated by Django 4.0.1 on 2022-01-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_post_amount_of_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='articles.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='amount_of_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
